name: Foo

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test:
    name: Foo
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        run: date
  bar:
    uses: ./.github/workflows/bar.yaml

